# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Put your favicon.ico into `hexo-site/source/` directory.
favicon: /favicon.ico

# Set default keywords (Use a comma to separate)
keywords: "Why, Liam, 李承璋"

# Set rss to false to disable feed link.
# Leave rss as empty to use site's feed link.
# Set rss to specific value if you have burned your feed already.
rss: /atom.xml

# Specify the date when the site was setup
since: 2003

# If you want to show the motto
# otherwise It shows the site description
motto: true

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash (/archives -> archives)
menu:
  Home: /
  Profile: true # Do not change
  Instagram: true # Show the Instagram
  Photo: /categories/photo/
  Video: /categories/video/
  Archives: /archives

# Social Links
# Key is the fontawsome keyname.
# Value is the target link (E.g. weibo: http://weibo.com/whyliam)
social:
  #LinkLabel: Link
  home: http://www.naaln.com
  weibo: http://weibo.com/210002567
  github-alt: https://github.com/liszd
  instagram: https://www.instagram.com/why_liam

# Sidebar Avatar
avatar: http://ww4.sinaimg.cn/large/72f96cbagw1f6f7g470iwj20u00u0wkr.jpg


# Automatically Excerpt. Not recommand.
# Please use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: true
  length: 170

# Discuess
# Duoshuo
duoshuo:
  shortname: naalnalbum
  share: true

# Disqus
disqus:
  shortname: 

# Share
# Baidu Share
# Available value:
#    button | slide
#baidushare:
##  type: button

# Share
#jiathis:
#add_this_id:



# Tencent analytics ID
# tencent_analytics:


# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO



# Algolia Search
algolia_search:
  enable: true
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"


reward_comment: 如果觉得我的文章对您有用，请随意打赏。您的支持将鼓励我继续创作！
wechatpay: http://ww1.sinaimg.cn/mw690/48910e01gw1evkbf70jcgj20cg0cidh5.jpg
alipay: http://ww3.sinaimg.cn/mw690/48910e01gw1evkbfendrjj20ci0ci0uf.jpg


instagram:
  enable: true
  userId: 428473662
  accessToken: 428473662.1677ed0.9774cad131cc42c3a4ec95a3b295fd40
  sortBy: random

lazyload: true
highlight: true
baidu_push: true

# Google Analytics
baidu_analytics:
google_analytics: UA-47966442-2
cnzz_analytics: 
tencent_analytics:


# Show PV/UV of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: false
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: false
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:


#site verification:
google_site_verification: ByVfaP_E3b9ZYRUGhNAUFSQKL8mJQwUehpQwoxJ5n-c
baidu_site_verification: 
qihu_site_verification: 

version: 0.0.1